import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';

import '../data/season_colour_guide.dart';
import '../models/colour_analysis_result.dart';

/// Generates and exports the user's colour-analysis report.
class ColourReportService {
  ColourReportService._();

  static Future<Uint8List> generateBytes({
    required ColourAnalysisResult result,
  }) async {
    final profile = SeasonColourGuide.forSeason(result.season);
    final document = PdfDocument();
    document.pageSettings.size = PdfPageSize.a4;

    try {
      final page = document.pages.add();
      final accent = _seasonColor(result.season);
      final dark = PdfColor(40, 36, 42);
      final muted = PdfColor(112, 104, 112);
      final soft = PdfColor(247, 243, 249);
      final white = PdfColor(255, 255, 255);

      page.graphics.drawRectangle(
        brush: PdfSolidBrush(accent),
        bounds: ui.Rect.fromLTWH(0, 0, page.getClientSize().width, 108),
      );

      _text(page, 'TiB', PdfStandardFont(PdfFontFamily.helvetica, 25, style: PdfFontStyle.bold), white, ui.Rect.fromLTWH(28, 23, 100, 30));
      _text(page, 'PERSONAL COLOUR ANALYSIS', PdfStandardFont(PdfFontFamily.helvetica, 10, style: PdfFontStyle.bold), white, ui.Rect.fromLTWH(28, 56, 300, 16));
      _text(page, result.season, PdfStandardFont(PdfFontFamily.helvetica, 22, style: PdfFontStyle.bold), white, ui.Rect.fromLTWH(300, 31, 240, 28), alignRight: true);
      _text(page, profile.dimension, PdfStandardFont(PdfFontFamily.helvetica, 10), white, ui.Rect.fromLTWH(300, 63, 240, 16), alignRight: true);

      var y = 132.0;
      _sectionTitle(page, 'Your result', y, accent);
      y += 30;
      _metricCard(page, 28, y, 158, 'Undertone', result.undertone, accent, dark);
      _metricCard(page, 202, y, 158, 'Brightness', result.brightness, accent, dark);
      _metricCard(page, 376, y, 158, 'Contrast', result.contrast, accent, dark);
      y += 84;

      _text(page, profile.description, PdfStandardFont(PdfFontFamily.helvetica, 11), muted, ui.Rect.fromLTWH(28, y, 510, 42));
      y += 55;

      _sectionTitle(page, 'Best colours', y, accent);
      y += 30;
      y = _drawSwatches(page, profile.bestColours, y, accent, dark);
      y += 10;

      _sectionTitle(page, 'Eye shadow colour advice', y, accent);
      y += 30;
      y = _drawSwatches(page, profile.eyeShadowColours, y, accent, dark);
      y += 10;

      _sectionTitle(page, 'Blush colour advice', y, accent);
      y += 30;
      y = _drawSwatches(page, profile.blushColours, y, accent, dark);
      y += 12;

      _sectionTitle(page, 'Season keywords', y, accent);
      y += 30;
      y = _drawKeywords(page, profile.keywords, y, accent, dark, soft);
      y += 15;

      _text(
        page,
        "Generated by TiB AI Personal Styling • ${DateFormat('dd MMM yyyy, h:mm a').format(DateTime.now())}",
        PdfStandardFont(PdfFontFamily.helvetica, 8),
        muted,
        ui.Rect.fromLTWH(28, y, 510, 16),
      );

      final guidePage = document.pages.add();
      _drawSeasonReference(guidePage);

      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  static Future<File> generateReport({
    required ColourAnalysisResult result,
  }) async {
    final bytes = await generateBytes(result: result);
    final directory = await getTemporaryDirectory();
    final fileName = 'TiB_Colour_Report_${result.season.replaceAll(' ', '_')}.pdf';
    final file = File('${directory.path}/$fileName');
    await file.writeAsBytes(bytes, flush: true);
    return file;
  }

  /// Saves a durable copy into the app Documents directory.
  /// On iOS the project exposes this directory through the Files app
  /// configuration, so the saved report remains available to the user.
  static Future<File> saveReport({
    required ColourAnalysisResult result,
  }) async {
    final bytes = await generateBytes(result: result);
    final safeSeason = result.season.replaceAll(RegExp(r'[^A-Za-z0-9_-]+'), '_');
    final fileName = 'TiB_Colour_Report_$safeSeason.pdf';
    final documentsDirectory = await getApplicationDocumentsDirectory();
    final file = File('${documentsDirectory.path}/$fileName');
    await file.writeAsBytes(bytes, flush: true);
    return file;
  }

  static Future<File> generateAndShare({
    required ColourAnalysisResult result,
    String? shareText,
  }) async {
    final file = await generateReport(result: result);
    await SharePlus.instance.share(
      ShareParams(
        title: 'TiB Colour Analysis Report',
        subject: 'My TiB Colour Analysis Report',
        text: shareText ?? 'My personal TiB colour analysis report.',
        files: [XFile(file.path)],
      ),
    );
    return file;
  }

  static void _sectionTitle(PdfPage page, String title, double y, PdfColor accent) {
    _text(page, title, PdfStandardFont(PdfFontFamily.helvetica, 16, style: PdfFontStyle.bold), PdfColor(40, 36, 42), ui.Rect.fromLTWH(28, y, 360, 22));
    page.graphics.drawRectangle(brush: PdfSolidBrush(accent), bounds: ui.Rect.fromLTWH(28, y + 26, 45, 3));
  }

  static void _metricCard(PdfPage page, double x, double y, double width, String label, String value, PdfColor accent, PdfColor dark) {
    page.graphics.drawRectangle(brush: PdfSolidBrush(PdfColor(250, 248, 251)), pen: PdfPen(PdfColor(225, 219, 228)), bounds: ui.Rect.fromLTWH(x, y, width, 66));
    page.graphics.drawEllipse(ui.Rect.fromLTWH(x + 12, y + 14, 16, 16), brush: PdfSolidBrush(accent));
    _text(page, label, PdfStandardFont(PdfFontFamily.helvetica, 8, style: PdfFontStyle.bold), PdfColor(120, 114, 122), ui.Rect.fromLTWH(x + 36, y + 12, width - 48, 12));
    _text(page, value, PdfStandardFont(PdfFontFamily.helvetica, 12, style: PdfFontStyle.bold), dark, ui.Rect.fromLTWH(x + 12, y + 34, width - 24, 18));
  }

  static double _drawSwatches(PdfPage page, List<String> names, double y, PdfColor accent, PdfColor dark) {
    const swatch = 72.0;
    const gapX = 10.0;
    const gapY = 48.0;
    const startX = 28.0;
    const columns = 6;

    for (var i = 0; i < names.length; i++) {
      final row = i ~/ columns;
      final col = i % columns;
      final x = startX + col * (swatch + gapX);
      final top = y + row * gapY;
      page.graphics.drawRectangle(
        brush: PdfSolidBrush(_colourFor(names[i], accent)),
        pen: PdfPen(PdfColor(230, 224, 232)),
        bounds: ui.Rect.fromLTWH(x, top, swatch, 27),
      );
      _text(page, names[i], PdfStandardFont(PdfFontFamily.helvetica, 6.6), dark, ui.Rect.fromLTWH(x, top + 30, swatch, 16), alignCenter: true);
    }

    final rows = (names.length / columns).ceil();
    return y + rows * gapY;
  }

  static double _drawKeywords(PdfPage page, List<String> keywords, double y, PdfColor accent, PdfColor dark, PdfColor soft) {
    var x = 28.0;
    var currentY = y;
    for (final keyword in keywords) {
      final width = 17 + keyword.length * 4.1;
      if (x + width > 530) {
        x = 28;
        currentY += 28;
      }
      page.graphics.drawRectangle(brush: PdfSolidBrush(soft), pen: PdfPen(accent, width: .6), bounds: ui.Rect.fromLTWH(x, currentY, width, 21));
      _text(page, keyword, PdfStandardFont(PdfFontFamily.helvetica, 7), dark, ui.Rect.fromLTWH(x + 5, currentY + 4, width - 10, 12), alignCenter: true);
      x += width + 7;
    }
    return currentY + 28;
  }

  static void _drawSeasonReference(PdfPage page) {
    final graphics = page.graphics;
    final profiles = SeasonColourGuide.profiles.values.toList();

    _text(page, 'TiB Season Colour Guide', PdfStandardFont(PdfFontFamily.helvetica, 22, style: PdfFontStyle.bold), PdfColor(40, 36, 42), ui.Rect.fromLTWH(28, 28, 500, 28));
    _text(page, 'Four-season reference based on the provided colour guide', PdfStandardFont(PdfFontFamily.helvetica, 10), PdfColor(112, 104, 112), ui.Rect.fromLTWH(28, 61, 500, 16));

    final positions = <ui.Rect>[
      ui.Rect.fromLTWH(28, 100, 248, 300),
      ui.Rect.fromLTWH(292, 100, 248, 300),
      ui.Rect.fromLTWH(28, 420, 248, 300),
      ui.Rect.fromLTWH(292, 420, 248, 300),
    ];

    for (var i = 0; i < profiles.length && i < positions.length; i++) {
      final profile = profiles[i];
      final rect = positions[i];
      final color = _seasonColor(profile.name);
      graphics.drawRectangle(brush: PdfSolidBrush(PdfColor(250, 248, 251)), pen: PdfPen(color, width: 1), bounds: rect);
      _text(page, profile.name.toUpperCase(), PdfStandardFont(PdfFontFamily.helvetica, 13, style: PdfFontStyle.bold), color, ui.Rect.fromLTWH(rect.left + 14, rect.top + 14, rect.width - 28, 18));
      _text(page, profile.dimension, PdfStandardFont(PdfFontFamily.helvetica, 10, style: PdfFontStyle.bold), PdfColor(40, 36, 42), ui.Rect.fromLTWH(rect.left + 14, rect.top + 40, rect.width - 28, 16));
      _text(page, profile.description, PdfStandardFont(PdfFontFamily.helvetica, 8.5), PdfColor(112, 104, 112), ui.Rect.fromLTWH(rect.left + 14, rect.top + 65, rect.width - 28, 42));
      _drawSwatches(page, profile.bestColours.take(6).toList(), rect.top + 118, color, PdfColor(40, 36, 42));
      _text(page, 'Eye: ${profile.eyeShadowColours.take(4).join(', ')}', PdfStandardFont(PdfFontFamily.helvetica, 7), PdfColor(70, 64, 72), ui.Rect.fromLTWH(rect.left + 14, rect.bottom - 49, rect.width - 28, 20));
      _text(page, 'Blush: ${profile.blushColours.take(4).join(', ')}', PdfStandardFont(PdfFontFamily.helvetica, 7), PdfColor(70, 64, 72), ui.Rect.fromLTWH(rect.left + 14, rect.bottom - 27, rect.width - 28, 20));
    }
  }

  static void _text(PdfPage page, String text, PdfFont font, PdfColor color, ui.Rect bounds, {bool alignCenter = false, bool alignRight = false}) {
    final textSize = font.measureString(text);
    var x = bounds.left;
    if (alignRight) {
      x = bounds.right - textSize.width;
    } else if (alignCenter) {
      x = bounds.left + (bounds.width - textSize.width) / 2;
    }
    if (x < bounds.left) x = bounds.left;
    page.graphics.drawString(
      text,
      font,
      brush: PdfSolidBrush(color),
      bounds: ui.Rect.fromLTWH(x, bounds.top, textSize.width + 2, bounds.height),
    );
  }

  static PdfColor _seasonColor(String season) {
    switch (season) {
      case 'Winter': return PdfColor(66, 92, 150);
      case 'Summer': return PdfColor(139, 105, 182);
      case 'Spring': return PdfColor(224, 145, 82);
      case 'Autumn': return PdfColor(157, 91, 55);
      default: return PdfColor(139, 105, 182);
    }
  }

  static PdfColor _colourFor(String name, PdfColor accent) {
    final key = name.toLowerCase();
    if (key.contains('white') || key.contains('ivory')) return PdfColor(245, 243, 238);
    if (key.contains('black')) return PdfColor(38, 36, 38);
    if (key.contains('charcoal')) return PdfColor(70, 73, 80);
    if (key.contains('navy')) return PdfColor(38, 57, 88);
    if (key.contains('blue') || key.contains('sapphire') || key.contains('cobalt')) return PdfColor(65, 115, 176);
    if (key.contains('lavender') || key.contains('lilac') || key.contains('mauve')) return PdfColor(176, 151, 193);
    if (key.contains('pink') || key.contains('rose') || key.contains('raspberry')) return PdfColor(211, 132, 155);
    if (key.contains('red') || key.contains('ruby') || key.contains('cranberry')) return PdfColor(167, 65, 74);
    if (key.contains('peach') || key.contains('apricot') || key.contains('coral')) return PdfColor(230, 141, 116);
    if (key.contains('yellow') || key.contains('gold')) return PdfColor(210, 174, 70);
    if (key.contains('green') || key.contains('olive') || key.contains('mint')) return PdfColor(108, 135, 82);
    if (key.contains('brown') || key.contains('camel') || key.contains('chocolate') || key.contains('sienna')) return PdfColor(143, 103, 74);
    if (key.contains('beige') || key.contains('cream') || key.contains('taupe')) return PdfColor(205, 186, 157);
    if (key.contains('grey') || key.contains('gray')) return PdfColor(154, 153, 157);
    return accent;
  }
}
