// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqP5GeWQnrqyRg3cYPe4-10lIPhUPIO7Q',
    appId: '1:494434706372:web:0d7fc536e0364a227e3a91',
    messagingSenderId: '494434706372',
    projectId: 'tib-ai-personal-styling',
    authDomain: 'tib-ai-personal-styling.firebaseapp.com',
    storageBucket: 'tib-ai-personal-styling.firebasestorage.app',
    measurementId: 'G-6W0VCE7Z0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_v1EqXYYHptNSB7JeWUYZt2_glwABaBU',
    appId: '1:494434706372:android:d7ccc01ba31212a67e3a91',
    messagingSenderId: '494434706372',
    projectId: 'tib-ai-personal-styling',
    storageBucket: 'tib-ai-personal-styling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWuwFtV6QRTjChhBxUIpipj5KzO6cDBRM',
    appId: '1:494434706372:ios:5b99ed6fe56207e57e3a91',
    messagingSenderId: '494434706372',
    projectId: 'tib-ai-personal-styling',
    storageBucket: 'tib-ai-personal-styling.firebasestorage.app',
    iosBundleId: 'com.example.tibAiPersonalStyling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWuwFtV6QRTjChhBxUIpipj5KzO6cDBRM',
    appId: '1:494434706372:ios:5b99ed6fe56207e57e3a91',
    messagingSenderId: '494434706372',
    projectId: 'tib-ai-personal-styling',
    storageBucket: 'tib-ai-personal-styling.firebasestorage.app',
    iosBundleId: 'com.example.tibAiPersonalStyling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqP5GeWQnrqyRg3cYPe4-10lIPhUPIO7Q',
    appId: '1:494434706372:web:c61b35d97a39a8027e3a91',
    messagingSenderId: '494434706372',
    projectId: 'tib-ai-personal-styling',
    authDomain: 'tib-ai-personal-styling.firebaseapp.com',
    storageBucket: 'tib-ai-personal-styling.firebasestorage.app',
    measurementId: 'G-Z9S5MY3T8S',
  );
}
