import 'dart:io';

import 'package:flutter/material.dart';

import '../core/constants/app_colors.dart';
import '../core/constants/app_gradients.dart';
import '../services/tib_model_service.dart';

/// A lightweight local preview of the user's TiB Model.
/// The scanned face remains the identity reference while the body silhouette
/// reflects the saved body-shape classification. The real AI try-on is still
/// generated by the backend when an outfit is selected.
class TibVirtualModelPreview extends StatelessWidget {
  const TibVirtualModelPreview({
    super.key,
    required this.model,
    this.height = 320,
  });

  final TibModelProfile model;
  final double height;

  @override
  Widget build(BuildContext context) {
    final face = model.faceFile;
    final body = model.bodyFile;

    if (body != null && body.existsSync()) {
      return ClipRRect(
        borderRadius: BorderRadius.circular(24),
        child: Image.file(
          body,
          height: height,
          width: double.infinity,
          fit: BoxFit.cover,
        ),
      );
    }

    final bodyWidth = switch (model.bodyShape) {
      'Pear' => 138.0,
      'Apple' => 142.0,
      'Hourglass' => 112.0,
      'Inverted Triangle' => 150.0,
      _ => 124.0,
    };

    return Container(
      height: height,
      width: double.infinity,
      decoration: BoxDecoration(
        gradient: AppGradients.soft,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: AppColors.primarySoft),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            width: 86,
            height: 86,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: AppColors.surfaceMuted,
              border: Border.all(color: AppColors.primarySoft, width: 3),
            ),
            child: face != null && face.existsSync()
                ? Image.file(face, fit: BoxFit.cover)
                : const Icon(
                    Icons.person_rounded,
                    size: 48,
                    color: AppColors.primary,
                  ),
          ),
          const SizedBox(height: 8),
          Container(
            width: bodyWidth,
            height: 175,
            decoration: BoxDecoration(
              gradient: AppGradients.premium,
              borderRadius: BorderRadius.circular(70),
              border: Border.all(color: AppColors.primarySoft),
            ),
            child: const Icon(
              Icons.checkroom_rounded,
              size: 42,
              color: AppColors.primaryDark,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            '${model.bodyShape} body · ${model.faceShape} face',
            style: const TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.w800,
              color: AppColors.textSecondary,
            ),
          ),
        ],
      ),
    );
  }
}
