import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../core/constants/app_colors.dart';
import '../../services/live_consultancy_service.dart';

class ConsultationManagementScreen extends StatefulWidget {
  const ConsultationManagementScreen({super.key});
  @override State<ConsultationManagementScreen> createState() => _ConsultationManagementScreenState();
}
class _ConsultationManagementScreenState extends State<ConsultationManagementScreen> {
  String _filter = 'all';
  @override void initState() { super.initState(); LiveConsultancyService.setConsultantPresence(true); }
  @override void dispose() { LiveConsultancyService.setConsultantPresence(false); super.dispose(); }
  @override Widget build(BuildContext context) {
    const filters = {'all':'All','waiting_for_consultant':'Waiting','assigned':'Assigned','consultant_replied':'Replied','resolved':'Resolved'};
    return Scaffold(backgroundColor: AppColors.background, appBar: AppBar(title: const Text('Live Consultancy')), body: Column(children: [
      StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream: LiveConsultancyService.onlineConsultantsStream(), builder: (_, s) { final n=s.data?.docs.length??0; return Container(margin: const EdgeInsets.fromLTRB(16,8,16,6), padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: AppColors.secondary.withValues(alpha:.55), borderRadius: BorderRadius.circular(17)), child: Row(children:[Icon(Icons.circle,size:9,color:n>0?Colors.green:AppColors.textMuted),const SizedBox(width:8),Expanded(child:Text(n==0?'No consultants online':'$n consultant${n==1?'':'s'} online',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800))),const Text('LIVE',style:TextStyle(fontSize:9,fontWeight:FontWeight.w800,color:AppColors.primary))])); }),
      SingleChildScrollView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.fromLTRB(16,2,16,8),child:Row(children:filters.entries.map((e)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(selected:_filter==e.key,label:Text(e.value),onSelected:(_)=>setState(()=>_filter=e.key)))).toList())),
      Expanded(child:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:LiveConsultancyService.consultationsStream(status:_filter=='all'?null:_filter),builder:(_,s){if(s.hasError)return Center(child:Text('Unable to load consultations: ${s.error}'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final docs=s.data!.docs;if(docs.isEmpty)return const Center(child:Text('No consultations found.'));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:docs.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){final d=docs[i].data();final unread=(d['unreadForConsultant'] as num?)?.toInt()??0;return Card(elevation:0,child:ListTile(leading:CircleAvatar(backgroundColor:AppColors.secondary,child:const Icon(Icons.person_outline_rounded,color:AppColors.primary)),title:Row(children:[Expanded(child:Text(d['userName'] as String???'TiB User',style:const TextStyle(fontWeight:FontWeight.w800))),if(unread>0)Text('$unread unread',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:AppColors.primary))]),subtitle:Text(d['assignedConsultantName'] as String???d['lastMessage'] as String???d['email'] as String???'New consultation',maxLines:2,overflow:TextOverflow.ellipsis),trailing:Text((d['status'] as String???'open').replaceAll('_',' '),style:const TextStyle(fontSize:9.5,fontWeight:FontWeight.w800)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ConsultantChatScreen(uid:docs[i].id,userName:d['userName'] as String???'TiB User')))));});}))]));
  }
}
class ConsultantChatScreen extends StatefulWidget { final String uid,userName; const ConsultantChatScreen({super.key,required this.uid,required this.userName}); @override State<ConsultantChatScreen> createState()=>_ConsultantChatScreenState(); }
class _ConsultantChatScreenState extends State<ConsultantChatScreen> {
  final _composer=TextEditingController(); bool _sending=false;
  @override void initState(){super.initState();LiveConsultancyService.setConsultantPresence(true);LiveConsultancyService.assignToCurrentConsultant(widget.uid);LiveConsultancyService.markMessagesRead(widget.uid,by:'consultant');}
  @override void dispose(){_composer.dispose();super.dispose();}
  Future<void> _send()async{final text=_composer.text.trim();if(text.isEmpty||_sending)return;final name=FirebaseAuth.instance.currentUser?.displayName?.trim();setState(()=>_sending=true);_composer.clear();try{await LiveConsultancyService.sendConsultantMessage(uid:widget.uid,text:text,consultantName:name==null||name.isEmpty?'TiB Consultant':name);await LiveConsultancyService.markMessagesRead(widget.uid,by:'consultant');}finally{if(mounted)setState(()=>_sending=false);}}
  Future<void> _resolve()async{await LiveConsultancyService.setStatus(widget.uid,'resolved');if(mounted)Navigator.pop(context);}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.background,appBar:AppBar(title:Text(widget.userName),actions:[IconButton(onPressed:_resolve,icon:const Icon(Icons.check_circle_outline_rounded))]),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:LiveConsultancyService.conversationMessages(widget.uid),builder:(_,s){if(s.hasError)return Center(child:Text('Unable to load messages: ${s.error}'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final docs=s.data!.docs;return Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:docs.length,itemBuilder:(_,i){final d=docs[i].data();final c=d['senderType']=='consultant';return Align(alignment:c?Alignment.centerRight:Alignment.centerLeft,child:Container(constraints:const BoxConstraints(maxWidth:330),margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.symmetric(horizontal:14,vertical:11),decoration:BoxDecoration(color:c?AppColors.primary:AppColors.surface,borderRadius:BorderRadius.circular(17)),child:Text(d['text'] as String???'',style:TextStyle(color:c?Colors.white:AppColors.textPrimary,fontSize:12.5)));})),SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(15,7,15,12),child:Row(children:[Expanded(child:TextField(controller:_composer,maxLines:4,minLines:1,textInputAction:TextInputAction.send,onSubmitted:(_)=>_send(),decoration:InputDecoration(hintText:'Reply to customer…',filled:true,fillColor:AppColors.surface,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18))))),const SizedBox(width:8),IconButton(onPressed:_sending?null:_send,icon:const Icon(Icons.send_rounded))]))]);}));
}